language: python
os:
- linux
services:
- docker
python:
- '3.6'
install:
- pip install .
script: 'true'
deploy:
- provider: script
  script: "./devel/travis_deploy.sh"
  on:
    tags: true
  skip_cleanup: true
env:
  global:
  - secure: wMh626tObe2AOY+wCJUbcyKbJfjD52D7wxlTREIt248Yq81ItCktj9WoIOHPgRVn9Xxfox37291xhl3YzkNPnLl4whgG3qPjlmGshsbjzl8MJXW0GYWBZXEy259rfgKvR9qnSnPQVR3tc/oWxOy+D9VoNiP4WaRvyyHTAmqN1wPPonQQqSiI8IHlkMTLPO6lBvLUzKJJxoRGu+LGOKtGhe6kxrdpIaea+4lVW0KzDWj/iEl1t0LwYGvVI07e8iLDJL9Sg54XSr12vyysSHEjXKl8i7RLqtMGx/FLT26llsSzwWt/iwXjhxaXxRvNSgKI05ykDgrY503L0VIDyLD94CubiZqmHax4ljOenb/XDxMMfn0LUeKeB33lK8kCarSFx0vgxKmE2YROsrs2tMXN4HrvE1mJyrkuIMOjm9ncXPA33dhi5lRd2ulXLx9P6SLeTOS49nI/audYsI5/ul+7uVCPrAbS396LvaAou9FfbfKbMdAzFGRn9gJHZHhp6adlBSj+kGToE4UlEbthkn7g69wh99CdLV8JxfiQxW9iESVWnFE8arm1q8Z7vLoybB21ilkoz++Bq1O0ulYuCFOknB7xUuMWS/qzxJlarBnLDzrVanh2HAjnurdq4Wjtdxo0a39JDzH+W0N3MwTkvi2N1LDSEvh4OeJ6tVSFK/Wh5GU=
  - secure: MPgN9zVLDPyOxr50aZeNhTSBuTPKvIaibO0nIdSCKMRghKmbPJfa7sKJYZ3HfIb1Orf5VNsBvw7fiJL5Gcu+/PTSBtqb1BzRUy9khrmGCdEoa0aqe1LiRT4BuRET6rdlPR1KbbH1ce2GIoRbkE2qyrC8FBseuMI0PBYYMPqGxxRRZ4YAlFfxZOkf2R7RDAI6UyJyO0BhBQIMbppdO0dQkrK+WKwb6DTDYIeXKdEPaaCQR4qQowA37Bud3i4WlXUNwAKCvOrytuTsE/M0DAl4s6WiLeSgYDW/LgrWhnkgu2OvWicISmu5FxrCbQw2zBjypAeoXTiHwM3729UqS3rbiXoGOtho7cPwTSjfg0ILRJmGLIragS+8TtPxfkuFmuYk0BR4B138QXVx/Etrt9qeY5pfyoyLbQ2o8GWZIDczd48buEVCzsJsc/vD2b04b7/yi6T1rPlSX+J2p0fjxtI1PvZ7AyXRzG2DX2aVUatIubmLi0PXL22xkRZ2zwX1YS23MbEljlvWQKbn+huu0GtlLjL2E6kzwjjICnBBbXp4jHWkPVkxdLM3BCTSSSRiG25ag03G4uWelVupYirs1IG8mK5lpHOCo4ReJDTpYsWrhlWAV9a8byrOGTGij3789x4GUfH7H1fEUhw7D1ZPd4dId8c/z2sQHNZTtSA9hyHa8AE=
  - secure: knyOUDH8UNXziQG2HlnQGIp2cR4cvEMo6ppKbyW5LUNNu2pP/EULwsaeGyYc9MY85eJ2NH8hTVd1IZxlOwo6xNNHoRd0TqroNGdWWSmMlO7zt1jo1OyAyX98opLoi0XPqR8pbu/vv27Usenf1TkyjuQnXekvGoQ8UKiQL3+0tawZK+RK1RMjZ9vKvBMv8bfs8qACqOwbkH1DzT7TfWIlHkq6MtMIm4avT/oU3rLSbxLBhHOYxKtHqKKEHjCUus7EmoOP8ZJuuWEje9g6V5yjPYNTHfDuqdevRKxHfXUNlV1GPZ0eddMmXSgkxXjVx8BrzFoIC3JKLQ/uVKKvEy3sTyRWOvL/wNPNn8l+QEO8aznjJG+02WMs8WrFU60kMygqszzNVsRm0HnOt1PuLkY9Wr4gQRjxYc3iYQ32acbGn4OkfTMHWMIlEWqXn/HqveRrUh/0JEI1dH/enB9pmXyh51+6aZh9PqnfMYPezXTVM9FFnDM4AvZ+tqGtiQbebStoOLqlt4EfMQ6sBVoN2mkPD/ERss2e0LTYzCPVZGRg9C5yWopOWHKHXZuAMobIqqltc4Cy0bIAkcYZ6jQNNNDoPakuFUT4dgkgUBbo1GdLaHISMrBOmPdtjJYO3zCucfGhJyHy824K7IJRbYJaZRk3tCgBxhpjKdpYQowkDAvW7wI=
